"""add water_intake table

Revision ID: 472129e31dca
Revises: 15560e7e6080
Create Date: 2026-09-29 09:24:50.649882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472129e31dca'
down_revision: Union[str, Sequence[str], None] = '15560e7e6080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_intakes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_user_water_date')
    )
    op.create_index(op.f('ix_water_intakes_log_date'), 'water_intakes', ['log_date'], unique=False)
    op.create_index(op.f('ix_water_intakes_user_id'), 'water_intakes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_intakes_user_id'), table_name='water_intakes')
    op.drop_index(op.f('ix_water_intakes_log_date'), table_name='water_intakes')
    op.drop_table('water_intakes')
    # ### end Alembic commands ###
